service: soupilar
image: dinclas/soupilar
servers:
  - 116.202.49.57
# Docker image registry credentials
registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  username: dinclas

  password:
    - KAMAL_REGISTRY_PASSWORD